site_name: Internet Protocol
nav:
  - Home: index.md
  - Example: example.md
  - Websocket: websocket.md
  - HTTP: http.md
  - Json: json.md
  - Raw: raw.md
theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - tables
  - md_in_html
copyright: Copyright &copy; 2024 plugin made by Natha Miguel.
